name: Deploy to outpost/coup

on:
  push:
    branches: ["_feat/board_graphics"] # TODO: Scope only to main pushes

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Backend to Coup
        run: |
          flyctl deploy \
          -c fly.citadel.toml \
          -a truncate-coup \
          --build-arg TR_COMMIT="$(git rev-parse HEAD)" \
          --build-arg TR_MSG="$(git log -1 --pretty=%B | head -n 1 | sed "s/\"/'/g")" \
          --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Deploy Frontend to Outpost
        run: |
          flyctl deploy \
          -c fly.client.toml \
          -a truncate-outpost \
          --build-arg TR_COMMIT="$(git rev-parse HEAD)" \
          --build-arg TR_MSG="$(git log -1 --pretty=%B | head -n 1 | sed "s/\"/'/g")" \
          --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
